name: Docs Deploy Preview

on:
  pull_request:
    paths:
      - "docs/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: docs/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: ./docs

      - name: Build
        run: npm run build
        working-directory: ./docs

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_IGNITE_HQ }}"
          expires: 7d
          target: docs.ignite.com
          projectId: ignite-hq
