name: Test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*
            !**/*.md
      - uses: actions/setup-go@v2
        if: env.GIT_DIFF
        with:
          go-version: 1.18
      - run: ./scripts/test-unit
        if: env.GIT_DIFF
