name: Lint
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - develop
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Set up Go
        uses: actions/setup-go@v2
        if: env.GIT_DIFF
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@master
        if: env.GIT_DIFF
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.45.2
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
